<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hafidhsanjaya2gmail.com  Not you</name>
   <tag></tag>
   <elementGuidId>8bf220cd-843f-4755-9403-2e6164968dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_block']/span/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fsm.fwn.fcg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8627e6f3-4e8b-4830-939a-3aab6f0a6401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fsm fwn fcg</value>
      <webElementGuid>eba96819-4dd0-46bd-89d0-e4b1b8ff3e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hafidhsanjaya2@gmail.com · Not you?</value>
      <webElementGuid>457795ba-c1e7-4fb4-a82b-039cb02ebef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_block&quot;)/span[@class=&quot;_97w1 _50f6&quot;]/div[@class=&quot;_85el&quot;]/div[@class=&quot;fsm fwn fcg&quot;]</value>
      <webElementGuid>f6e58de8-0b87-4e07-b61d-a173e2838637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_block']/span/div/div[2]</value>
      <webElementGuid>75a77912-a011-427f-8c33-8fbf6d21336e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in as Hafidh Sanjaya'])[1]/following::div[1]</value>
      <webElementGuid>48205142-d224-430e-88c5-eb29014a5381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hafidhsanjaya2@gmail.com']/parent::*</value>
      <webElementGuid>e552cde2-bc7d-4b83-94bc-79ff58d612ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]</value>
      <webElementGuid>805a23e8-c3f5-4e2b-8995-d58a98ba8525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'hafidhsanjaya2@gmail.com · Not you?' or . = 'hafidhsanjaya2@gmail.com · Not you?')]</value>
      <webElementGuid>fe8d1691-0798-4989-ab41-cf981c0c8d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
